### ISSUE TITLE
Upload video testimonials to YouTube

### ISSUE THREAD

**Issue by pat-lego** [AES-Outreach/Outreach-Wiki#106]
The YouTube channel now has a Playlist called `Client Meetings` which will be used to store the client interviews that Frank had with other vendors.

This will allow developers and management to see what others said about their current organizational issues.

**Comment by frankbouchard** [comment]
Can you guys provide me credentials to the youtube channel so I can upload?

**Comment by pat-lego** [comment]
Its only me who has it for now do you have it on a USB key or something?
