### ISSUE TITLE
Create the workflow for submission

### ISSUE THREAD

**Issue by pat-lego** [AES-Outreach/Outreach-Wiki#57]
Create a flowchart diagram explaining which tables need to be inserted into and mapped to what fields (including any special logic). 

- [ ] Do one for Workshops
- [ ] Do one for groups

Mockup is here: https://www.draw.io/?state=%7B%22folderId%22:%2215R90Bc6vl17XXr26AE5jbIybDdrn-ejT%22,%22action%22:%22create%22,%22userId%22:%22101975897462115098703%22%7D#G18ds9DQA_bg-VE4ckW8XMJqX-Q9Ue5ItK

child of AES-Outreach/Outreach-Wiki#54
depends on  AES-Outreach/Outreach-Wiki#56

**Comment by alexseguin** [comment]
https://drive.google.com/file/d/1te92fB6ciMSQVkEqwRNbQQe-TtOyc5pI/view?usp=sharing
